apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
      name: postgres-pod
  template:
    metadata: #Dictionary
      name: postgres-pod
      labels: #Dictionary within the metadata dictionary
        app: demo-voting-app
        name: postgres-pod

    spec:
      containers: #List/Array
        - name: postgres
          image: postgres:10.4 #version 9.4 didn't work
          ports:
            - containerPort: 5432 #default port that postgres listens on

