apiVersion: v1 #String
kind: Service #String
metadata: #Dictionary
    name: redis
    labels: #Dictionary within a dictionary
      name: redis-service
      app: demo-voting-app

spec:
#   type: ClusterIP  not needed because it's the default type
    ports: #List/Array
        - targetPort: 6379 #optional-default is same as Port
          port: 6379 #mandatory

    selector: #under selector we provide a list of filters to match pod labels
        app: demo-voting-app #from the pods that you want the service to connect to
        name: redis-pod #from the pods that you want the service to connect to