apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
      name: worker-app-pod
  template:
    metadata: #Dictionary
      name: worker-app-pod
      labels: #Dictionary within the metadata dictionary
        app: demo-voting-app
        name: worker-app-pod

    spec:
      containers: #List/Array
        - name: worker-app
          image: dockersamples/examplevotingapp_worker

